major overhaul; added exit option

diff --git a/xrandr-dmenu b/xrandr-dmenu
--- a/xrandr-dmenu
+++ b/xrandr-dmenu
@@ -2,72 +2,116 @@
 #
 # Setup outputs with xrandr as a backend and dmenu as a frontend
 #
-# external commands: cat, cut, dmenu, grep, sed, xrandr
+# external commands: cat, cut, dmenu, grep, sed, wc, xrandr
 # Released under GPLv2
 
 typeset XRANDR_TXT # readonly; stdout of running xrandr without any options
 typeset -A OUTPUT_CONFIGURED # key=connected output name
-typeset OPT_MODE
-typeset OPT_ROTATION
+typeset OPT_MODE='auto'
+typeset OPT_ROTATION='normal'
+typeset -ir EXIT_CLEAN=7
+typeset -ir ERR_BAD_ARGS=257
+typeset -ir ERR_BAD_SELECTION=258
+typeset -ir ERR_NO_OPTIONS=259
+
+if ! command -v cat &>/dev/null; then
+  echo 'coreutils seem to be missing. You'\''re gonna have a bad time.' >&2
+  exit 255
+elif ! command -v grep &>/dev/null; then
+  echo 'grep seems to be missing. You'\''re gonna have a bad time.' >&2
+  exit 255
+elif ! command -v xrandr &>/dev/null; then
+  echo 'Ran xrandr-dmenu without xrandr? You'\''re gonna have a bad time.' >&2
+  exit 255
+elif ! command -v dmenu &>/dev/null; then
+  echo 'Ran xrandr-dmenu without dmenu? You'\''re gonna have a bad time.' >&2
+  exit 255
+elif ! xset q &>/dev/null; then
+  echo 'Woah there, cowboy! You need to run this from inside X!' >&2
+  exit 1
+fi
+
+XRANDR_TXT="$(xrandr)" || exit $?
+
+while [[ -n "$1" ]]; do
+  case "$1" in
+    (-m) OPT_MODE='change' ;;
+    (-M) OPT_MODE='no_change' ;;
+    (-r) OPT_ROTATION='change' ;;
+    (-R) OPT_ROTATION='no_change' ;;
+    (--help)
+      show_help
+      exit 0
+      ;;
+    (*)
+      show_help
+      exit 1
+      ;;
+  esac
+  shift
+done
+typeset -r XRANDR_TXT
+typeset -r OPT_MODE
+typeset -r OPT_ROTATION
+
+function () {
+  typeset output
+
+  for output in $(grep ' connected' <<< "${XRANDR_TXT}" | cut -d ' ' -f 1); do
+    OUTPUT_CONFIGURED[${output}]='false'
+  done
+}
 
 function main() {
-  local -i iteration
-  local max_iteration
-  local output
-  local mode
-  local rotation
-  local position
-  local xrandr_cmd
+  setopt xtrace
+  typeset prompt
+  typeset menu
+  typeset output
+  typeset mode
+  typeset rotation
+  typeset position
+  typeset xrandr_cmd
 
-  environment_check
+  # set primary output
+  prompt='Select primary output:'
+  output="$(menu_select "${prompt}" ${(k)=OUTPUT_CONFIGURED})" || bail $?
 
-  iteration=0
-  max_iteration=$[ ${(w)#OUTPUT_CONFIGURED} - 1 ]
-  xrandr_cmd='xrandr'
-
-  while [[ "$1" ]]; do
-    case "$1" in
-      -m) OPT_MODE='change' ;;
-      -M) OPT_MODE='no_change' ;;
-      -r) OPT_ROTATION='change' ;;
-      -R) OPT_ROTATION='no_change' ;;
-      --help)
-        show_help
-        exit 0
-        ;;
-      *)
-        show_help
-        exit 1
-        ;;
-    esac
-    shift
-  done
-
-  select_output 'Select primary output:' 'all' | read output
-  select_mode "${output}" | read mode
-  select_rotation "${output}" | read rotation
-  OUTPUT_CONFIGURED[${output}]='true'
   position='--primary'
-  xrandr_cmd+=" --output ${output} ${position} ${rotation} ${mode}"
-  while ! all_outputs_configured && (( $iteration <= $max_iteration )); do
-    select_output 'Select next output:' 'unconfigured' | read output
-    select_position "${output}" | read position
+  mode="$(select_mode ${output})" || bail $?
+  rotation="$(select_rotation ${output})" || bail $?
+
+  OUTPUT_CONFIGURED[${output}]='true'
+  xrandr_cmd="xrandr --output ${output} ${position} ${rotation} ${mode}"
+
+  # set additional outputs
+  prompt='Select next output:'
+  while ! all_outputs_configured; do
+    menu="$(list_unconfigured_outputs)"
+    output="$(menu_select ${prompt} ${=menu})" || bail $?
+
+    position="$(select_position ${output})" || bail $?
     if [[ "${position}" != '--off' ]]; then
-      select_mode "${output}" | read mode
-      select_rotation "${output}" | read rotation
+      mode="$(select_mode ${output})" || bail $?
+      rotation="$(select_rotation ${output})" || bail $?
     fi
+
     OUTPUT_CONFIGURED[${output}]='true'
     xrandr_cmd+=" --output ${output} ${position} ${rotation} ${mode}"
-    (( iteration++ ))
   done
 
-  ${=xrandr_cmd}
+  # do the deed
+  if ! ${=xrandr_cmd}; then
+    echo "Failed to execute xrandr command:\n${xrandr_cmd}"
+    bail 255
+  fi
+  unsetopt xtrace
 }
 
 function show_help() {
   << EOL
 usage: xrandr-dmenu [options]
 Setup X outputs position, mode, etc
+Input 'exit' at any point to quit.
 
 Options:
   -m  Select mode for outputs
@@ -78,87 +122,39 @@ EOL
 }
 
 ################################################################################
-# Uses dmenu to select an output. Skips menu if only 1 option is available.
-# Prints the name of the selected output to stdout
-# Global variables:
-#  OUTPUT_CONFIGURED
-# Arguments:
-#  $1=prompt
-#  $2=group of outputs. valid options are configured, unconfigured, all
-# Returns:
-#  257=bad arguments
-#  258=bad selection (TODO)
-#  259=no options available
-################################################################################
-function select_output() {
-  local -a menu
-  local output
-  local -ir err_bad_args=257
-  local -ir err_bad_selection=258
-  local -ir err_no_options=259
-
-  case "$2" in
-    'configured')
-      for output in ${(k)OUTPUT_CONFIGURED}; do
-        ${OUTPUT_CONFIGURED[$output]} && menu+=("$output")
-      done
-      ;;
-    'unconfigured')
-      for output in ${(k)OUTPUT_CONFIGURED}; do
-        ${OUTPUT_CONFIGURED[$output]} || menu+=("$output")
-      done
-      ;;
-    'all') menu=(${(k)OUTPUT_CONFIGURED}) ;;
-    *) return "${err_bad_args}" ;;
-  esac
-
-  case ${#menu} in
-    0) return "${err_no_options}" ;;
-    1) echo "${menu}" ;;
-    *) echo ${(F)menu} | dmenu -l 10 -p "$1" ;;
-  esac
-}
-
-################################################################################
 # Uses dmenu to select the position of a given output relative to an already
 # configured output. --same-as and --off are considered a position.
 # Prints in the form of xrandr option (eg, '--right-of DP1') to stdout
 # Global variables:
-#  OUTPUT_CONFIGURED
+#  ERR_BAD_ARG
 # Arguments:
 #  $1=name of output to configure
 # Returns:
-#  257=bad argument (TODO: check validity beyond existance)
-#  258=bad selection
-#  259=no configured outputs to relate to (ie, no anchor)
+#  ERR_BAD_ARG for no $1
 ################################################################################
 function select_position() {
-  local anchor
-  local selection
-  local -ir err_bad_arg=257
-  local -ir err_bad_selection=258
-  local -ir err_no_anchor=259
+  [[ -z $1 ]] && return "${ERR_BAD_ARG}"
 
-  [[ -z $1 ]] && return "${err_bad_arg}"
+  typeset output
+  typeset prompt
+  typeset -a menu
+  typeset anchor
+  typeset position
+  typeset selection
+  output="$1"
+  prompt="Select position of ${output}:"
 
-  select_output "Set $1 relative to:" 'configured' | read anchor
-  [[ $? -eq 257 ]] && return "${err_no_anchor}"
-
-  echo "left of ${anchor}
-right of ${anchor}
-above ${anchor}
-below ${anchor}
-mirror ${anchor}
-off" | dmenu -l 10 -p "Select position of $1:" | read selection
+  for anchor in $(list_configured_outputs); do
+    for position in 'left of' 'right of' 'above' 'below' 'same as'; do
+      menu+=("${position} ${anchor}")
+    done
+  done
+  menu+=('off')
+  selection="$(menu_select "${prompt}" ${menu})" || return $?
 
   case "${selection[(w)1]}" in
-    left) echo "--left-of ${anchor}" ;;
-    right) echo "--right-of ${anchor}" ;;
-    above) echo "--above ${anchor}" ;;
-    below) echo "--below ${anchor}" ;;
-    mirror) echo "--same-as ${anchor}" ;;
-    off) echo "--off" ;;
-    *) return "${err_bad_selection}" ;;
+    (left|right|same) echo "--${selection/ /-}" ;;
+    (above|below|mirror|off) echo "--${selection}" ;;
   esac
 }
 
@@ -169,19 +165,22 @@ off" | dmenu -l 10 -p "Select position of $1:" | read selection
 # Global variables:
 #  XRANDR_TXT
 #  OPT_MODE
+#  ERR_BAD_ARGS
 # Arguments:
 #  $1 - name of which output we are working with
 # Returns:
-#  257=bad arguements; given output ($1) not found/connected (TODO)
-#  258=bad selection
+#  ERR_BAD_ARGS
 ################################################################################
 function select_mode() {
-  local menu
-  local selection
-  local -ir err_bad_args=257
-  local -ir err_bad_selection=258
+  [[ -z $1 ]] && return "${ERR_BAD_ARGS}"
 
-  [[ -z $1 ]] && return "${err_bad_args}"
+  typeset output
+  typeset prompt
+  typeset menu
+  typeset selection
+  output="$1"
+  prompt="Select mode for ${output}:"
+
 
   if [[ "${OPT_MODE}" == 'auto' ]]; then
     echo '--auto'
@@ -189,21 +188,19 @@ function select_mode() {
     echo ''
   else
     # TODO: make this not ugly. A better sed should negate the need for cut/grep
-    # Should probably parse (sed) seperately then assign to the array. Or not
-    # use an array at all.
     menu="$(echo \"${XRANDR_TXT}\" \
-      | sed -n '/^'$1' /,/^[^ ]/ s/ * //p' \
+      | sed -n '/^'${output}' /,/^[^ ]/ s/ * //p' \
       | cut -d ' ' -f 1 \
       | grep x \
       | cat <(echo auto) -)"
 
-    echo "${menu}" | dmenu -l 10 -p "Select mode for $1:" | read selection
+    selection="$(menu_select "${prompt}" ${=menu})" || bail $?
 
-    case "${selection}" in
-      'auto') echo '--auto' ;;
-      *x*) echo "--mode ${selection}" ;;
-      *) return "${err_bad_selection}" ;;
-    esac
+    if [[ 'auto' == "${selection}" ]]; then
+      echo '--auto'
+    else
+      echo "--mode ${selection}"
+    fi
   fi
 }
 
@@ -212,43 +209,89 @@ function select_mode() {
 # xrandr option format (eg '--rotate inverted') to stdout
 # Global variables:
 #  OPT_ROTATION
+#  ERR_BAD_ARGS
 # Arguments:
 #  $1 - name of which output we are working with
 # Returns:
-#  257=bad arguements; given output ($1) not found/connected (TODO)
-#  258=bad selection (TODO)
+#  ERR_BAD_ARGS
 ################################################################################
 function select_rotation() {
-  local selection
-  local -ir err_bad_args=275
-  local -ir err_bad_selection=258
+  [[ -z $1 ]] && return "${ERR_BAD_ARGS}"
 
-  [[ -z $1 ]] && return "${err_bad_args}"
+  typeset menu
+  typeset prompt
+  prompt="Select rotation of $1:"
+  menu=('normal' 'inverted' 'left' 'right')
 
   if [[ "${OPT_ROTATION}" == 'normal' ]]; then
     echo '--rotate normal'
   elif [[ "${OPT_ROTATION}" == 'no_change' ]]; then
     echo ''
   else
-    echo "normal\ninverted\nleft\nright" \
-      | dmenu -l 10 -p "Select rotation of $1:" \
-      | read selection
-    echo "--rotate ${selection}"
+    echo -n "--rotate ${selection}"
+    menu_select "${prompt}" ${menu} || bail $?
   fi
 }
 
 ################################################################################
-# Checks to see if all the outputs have been configured
-# global variables:
-#  OUTPUT_CONFIGURED
-# Arguments:
+# Uses dmenu to select an option. Undisplayed 'exit' option will return code 
+# ${EXIT_CLEAN} to trigger an abort to the script. Validates to make sure the
+# selection is an option. If there is only 1 option, it will automatically
+# choose it. Prints selection to stdout
+# Global variables:
 #  none
+# Arguments:
+#  $1=prompt
+#  $2+=menu items
 # Returns:
-#  0 - all outputs are configured
-#  257 - at least 1 output not configured
+#  ERR_BAD_ARGS=bad arguments
+#  EXIT_CLEAN=user requested exit
 ################################################################################
+function menu_select() {
+  [[ -z "$2" ]] && return ${ERR_BAD_ARGS}
+
+  typeset selection
+  typeset item
+  typeset prompt
+  typeset -a menu
+  prompt="$1"
+
+  shift
+  for item ($*) menu+=("${item}")
+
+  if [[ ${#menu} == 1 ]]; then
+    echo "${menu}"
+  else
+    while [[ -z "${menu[(r)${selection}]}" ]]; do
+      echo "${(F)menu}" | dmenu -p "${prompt}" | read selection
+      [[ "${(L)selection}" == 'exit' ]] && return ${EXIT_CLEAN}
+    done
+    echo "${selection}"
+  fi
+}
+
+function list_configured_outputs() {
+  typeset -a list
+  typeset output
+
+  for output in ${(k)OUTPUT_CONFIGURED}; do
+    ${OUTPUT_CONFIGURED[$output]} && list+=("${output}")
+  done
+  echo "${(F)list}"
+}
+
+function list_unconfigured_outputs() {
+  typeset -a list
+  typeset output
+
+  for output in ${(k)OUTPUT_CONFIGURED}; do
+    ${OUTPUT_CONFIGURED[$output]} || list+=("${output}")
+  done
+  echo "${(F)list}"
+}
+
 function all_outputs_configured() {
-  local config
+  typeset config
 
   for config in ${OUTPUT_CONFIGURED}; do
     $config || return 257
@@ -257,39 +300,11 @@ function all_outputs_configured() {
   return 0
 }
 
-function environment_check() {
-  if ! command -v cat &>/dev/null; then
-    echo 'You seem to be missing coreutils. You'\''re gonna have a bad time.' >&2
-    exit 255
-  elif ! command -v grep &>/dev/null; then
-    echo 'grep seems to be missing. You'\''re gonna have a bad time.' >&2
-    exit 255
-  elif ! command -v xrandr &>/dev/null; then
-    echo "Try xrandr-dmenu without xrandr, and you're gonna have a bad time." >&2
-    exit 255
-  elif ! command -v dmenu &>/dev/null; then
-    echo "Try xrandr-dmenu without dmenu, and you're gonna have a bad time." >&2
-    exit 255
-  elif ! xset q &>/dev/null; then
-    echo 'Woah there, cowboy! You need to run this from inside X!' >&2
-    exit 1
-  fi
+function bail() {
+  [[ "$1" == ${EXIT_CLEAN} ]] && exit 0 || exit "$1"
 }
 
-function initialize_globals() {
-  local output
-
-  OPT_MODE='auto'
-  OPT_ROTATION='normal'
-  XRANDR_TXT="$(xrandr)"
-  for output in $(grep ' connected' <<< "${XRANDR_TXT}" | cut -d ' ' -f 1); do
-    OUTPUT_CONFIGURED[${output}]='false'
-  done
-}
-
-initialize_globals
-readonly XRANDR_TXT
-main $@
+main
 
 ################################################################################
 # vim filetype=zsh autoindent expandtab shiftwidth=2 tabstop=2
