removed PRIMARY and CONNECTED_OUTPUT globals; lots of little stuff

diff --git a/xrandr-dmenu b/xrandr-dmenu
--- a/xrandr-dmenu
+++ b/xrandr-dmenu
@@ -2,204 +2,227 @@
 #
 # Setup outputs with xrandr as a backend and dmenu as a frontend
 #
-# Dependancies: dmenu, sed, xrandr, zsh
+# external commands: cat, cut, dmenu, grep, sed, xrandr
+# Released under GPLv2
 
-# r/o globals (set in init_global_vars)
-declare XRANDR_READ_IN
-declare -a CONNECTED_OUTPUT
-
-# r/w globals
-declare -A OUTPUT_CONFIGURED # key=output name
-declare PRIMARY #boolean for if we have set the primary output yet
+typeset XRANDR_TXT # readonly; stdout of running xrandr without any options
+typeset XRANDR_CMD # the actual xrandr command we will run at the end
+typeset -A OUTPUT_CONFIGURED # key=connected output name
 
 function main() {
+  local iteration
+  local max_iteration
   local output
   local mode
   local position
-  local failsafe
-  local xrandr_cmd
 
-  init_global_vars
-  failsafe=0
-  xrandr_cmd='xrandr'
+  environment_check
 
-  while [[ $(unconfigured_outputs) -ne 0 && $failsafe -lt 10 ]]; do
-    if ${PRIMARY} ; then
+  iteration=0
+  max_iteration=${(w)#OUTPUT_CONFIGURED}
+
+  while ! all_outputs_configured && (( $iteration <= $max_iteration )); do
+    if primary_set ; then
       select_output 'Select next output:' 'unconfigured' | read output
       select_mode "${output}" | read mode
       [[ "${mode}" != '--off' ]] && select_position "${output}" | read position
-      OUTPUT_CONFIGURED[${output}]=true
-      xrandr_cmd+=" --output ${output} ${position} ${mode}"
+      OUTPUT_CONFIGURED[${output}]='true'
     else
       select_output 'Select primary output:' 'all' | read output
       select_mode "${output}" | read mode
-      OUTPUT_CONFIGURED[${output}]=true
-      PRIMARY=true
-      xrandr_cmd+=" --output ${output} --primary ${mode}"
+      OUTPUT_CONFIGURED[${output}]='true'
+      position='--primary'
     fi
-    (( failsafe++ ))
+    XRANDR_CMD+=" --output ${output} ${position} ${mode}"
+    (( iteration++ ))
   done
 
-  ${=xrandr_cmd}
+  ${=XRANDR_CMD}
 }
 
 ################################################################################
 # Uses dmenu to select an output. Skips menu if only 1 option is available.
-# Prints the name of the output to stdout.
-# Globals:
-#  CONNECTED_OUTPUT
+# Prints the name of the selected output to stdout
+# Global variables:
 #  OUTPUT_CONFIGURED
 # Arguments:
 #  $1=prompt
 #  $2=group of outputs. valid options are configured, unconfigured, all
 # Returns:
-#  1=no options available
-#  2=invalid $2
+#  257=bad arguments
+#  258=bad selection (TODO)
+#  259=no options available
 ################################################################################
 function select_output() {
-  local -a output_list
-  
-  if [[ "$2" == 'configured' ]]; then
-    local out
-    for out in ${(k)OUTPUT_CONFIGURED}; do
-      ${OUTPUT_CONFIGURED[$out]} && output_list+=("$out")
-    done
-  elif [[ "$2" == 'unconfigured' ]]; then
-    local out
-    for out in ${(k)OUTPUT_CONFIGURED}; do
-      ${OUTPUT_CONFIGURED[$out]} || output_list+=("$out")
-    done
-  elif [[ "$2" == 'all' ]]; then
-    output_list=(${(k)OUTPUT_CONFIGURED})
-  else
-    return 2
-  fi
+  local -a menu
+  local output
+  local -ir err_bad_args=257
+  local -ir err_bad_selection=258
+  local -ir err_no_options=259
 
-  if [[ ${#output_list} -eq 0 ]]; then
-    return 1
-  elif [[ ${#output_list} -eq 1 ]]; then
-    echo "${output_list}"
-  else
-    print -l ${output_list} | dmenu -l 10 -p "$1"
-  fi
+  case "$2" in
+    'configured')
+      for output in ${(k)OUTPUT_CONFIGURED}; do
+        ${OUTPUT_CONFIGURED[$output]} && menu+=("$output")
+      done
+      ;;
+    'unconfigured')
+      for output in ${(k)OUTPUT_CONFIGURED}; do
+        ${OUTPUT_CONFIGURED[$output]} || menu+=("$output")
+      done
+      ;;
+    'all') menu=(${(k)OUTPUT_CONFIGURED}) ;;
+    *) return "${err_bad_args}" ;;
+  esac
+
+  case ${#menu} in
+    0) return "${err_no_options}" ;;
+    1) echo "${menu}" ;;
+    *) echo ${(F)menu} | dmenu -l 10 -p "$1" ;;
+  esac
 }
+
 ################################################################################
 # Uses dmenu to select the position of a given output relative to an already
 # configured output. Mirroring another output is considered a position.
-# Prints to stdout in the form of xrandr option (eg, '--right-of DP1')
-# Globals:
+# Prints in the form of xrandr option (eg, '--right-of DP1') to stdout
+# Global variables:
 #  OUTPUT_CONFIGURED
 # Arguments:
 #  $1=name of output to configure
 # Returns:
-#  1=no configured outputs to relate to
-#  2=$1 not given
-#  3=bad input
+#  257=bad argument (TODO: check validity beyond existance)
+#  258=bad selection
+#  259=no configured outputs to relate to (ie, no anchor)
 ################################################################################
 function select_position() {
-  local anchor  
-  local position
+  local anchor
+  local selection
+  local -ir err_bad_arg=257
+  local -ir err_bad_selection=258
+  local -ir err_no_anchor=259
+
+  [[ -z $1 ]] && return "${err_bad_arg}"
 
   select_output "Set $1 relative to:" 'configured' | read anchor
+  [[ $? -eq 257 ]] && return "${err_no_anchor}"
 
-  echo "left of $anchor
-right of $anchor
-above $anchor
-below $anchor
-mirror $anchor" | dmenu -l 10 -p "Select position of $1:" | read position
+  echo "left of ${anchor}
+right of ${anchor}
+above ${anchor}
+below ${anchor}
+mirror ${anchor}" | dmenu -l 10 -p "Select selection of $1:" | read selection
 
-  case "${position[(w)1]}" in
+  case "${selection[(w)1]}" in
     left) echo "--left-of ${anchor}" ;;
     right) echo "--right-of ${anchor}" ;;
     above) echo "--above ${anchor}" ;;
     below) echo "--below ${anchor}" ;;
     mirror) echo "--same-as ${anchor}" ;;
-    *)
-      echo 'Unexpected input' >&2
-      return 3
-      ;;
+    *) return "${err_bad_selection}" ;;
   esac
 }
 
 ################################################################################
 # Uses dmenu to display the detected mode options for a given output and lets
-# the user select a mode to use. Prints in xrandr option format
-# (eg, '--mode 800x600' or '--auto')
-# Globals:
-#  XRANDR_READ_IN
+# the user select a mode to use. Prints choice in xrandr option format
+# (eg, '--mode 800x600' or '--auto') to stdout
+# Global variables:
+#  XRANDR_TXT
 #  CONNECTED_OUTPUT
+#  XRANDR_CMD (via primary_set())
 # Arguments:
 #  $1 - name of which output we are working with
 # Returns:
-#  1=given output not found/connected (TODO)
-#  2=$1 not given
-#  3=Unexpected input
+#  257=bad arguements; given output ($1) not found/connected (TODO)
+#  258=bad selection
 ################################################################################
 function select_mode() {
-  local mode
   local menu
+  local selection
+  local -ir err_bad_args=257
+  local -ir err_bad_selection=258
+
+  if [[ -z $1 ]] && return "${err_bad_args}"
+
   # TODO: make this not ugly. A better sed should negate the need for cut/grep
   # Should probably parse (sed) seperately then assign to the array. Or not
   # use an array at all.
-  menu=$(echo "${XRANDR_READ_IN}" \
-    | sed -n '/^'$1' /,/^[^ ]/ s/ * / /gp' \
-    | cut -d ' ' -f 2 \
+  menu="$(echo \"${XRANDR_TXT}\" \
+    | sed -n '/^'$1' /,/^[^ ]/ s/ * //p' \
+    | cut -d ' ' -f 1 \
     | grep x \
-    | cat <(echo auto) -)
+    | cat <(echo auto) -)"
+  primary_set && menu+="\noff"
 
-  ${PRIMARY} && menu+="\noff"
-    
-  echo "${menu}" | dmenu -l 10 -p "Select mode for $1:" | read mode
+  echo "${menu}" | dmenu -l 10 -p "Select mode for $1:" | read selection
 
-  if [[ "${mode}" == "auto" ]]; then
-    echo '--auto'
-  elif [[ "${mode}" == 'off' ]]; then
-    echo '--off'
-  elif [[ "${mode}" == *x* ]]; then
-    echo "--mode ${mode}"
-  else
-    echo 'Unexpected input' >&2
-    return 3
-  fi
+  case "${selection}" in
+    'auto') echo '--auto' ;;
+    'off') echo '--off' ;;
+    *x*) echo "--mode ${selection}" ;;
+    *) return "${err_bad_selection}" ;;
+  esac
+}
+
+function primary_set() {
+  [[ "${XRANDR_CMD}" == *'--primary'* ]]
 }
 
 ################################################################################
-# prints the number of unconfigured outputs to stdout
-# Globals:
+# Checks to see if all the outputs have been configured
+# global variables:
 #  OUTPUT_CONFIGURED
 # Arguments:
 #  none
 # Returns:
-#  1 - arrays OUTPUT_CONFIGURED and CONNECTED_OUTPUT are different sizes.
+#  0 - all outputs are configured
+#  257 - at least 1 output not configured
 ################################################################################
-function unconfigured_outputs() {
-  local out
-  local integer count=0
+function all_outputs_configured() {
+  local config
 
-  [[ ${#OUTPUT_CONFIGURED} != ${#CONNECTED_OUTPUT} ]] && return 1
-  
-  for out in ${OUTPUT_CONFIGURED}; do
-    $out || (( count++ ))
+  for config in ${OUTPUT_CONFIGURED}; do
+    $config || return 257
   done
-  echo ${count}
+
+  return 0
 }
 
-function init_global_vars() {
-  local out
-
-  #TODO: make XRANDR_READ_IN and CONNECTED_OUTPUT readonly globals
-  XRANDR_READ_IN="$(xrandr)"
-  CONNECTED_OUTPUT=($(grep ' connec' <<< "${XRANDR_READ_IN}" | cut -d ' ' -f 1))
-  PRIMARY=false
-
-  for out in ${CONNECTED_OUTPUT}; do
-    OUTPUT_CONFIGURED[${out}]=false
-  done
+function environment_check() {
+  if ! command -v cat &>/dev/null; then
+    echo 'You seem to be missing coreutils. You'\''re gonna have a bad time.' >&2
+    exit 255
+  elif ! command -v grep &>/dev/null; then
+    echo 'grep seems to be missing. You'\''re gonna have a bad time.' >&2
+    exit 255
+  elif ! command -v xrandr &>/dev/null; then
+    echo "Try xrandr-dmenu without xrandr, and you're gonna have a bad time." >&2
+    exit 255
+  elif ! command -v dmenu &>/dev/null; then
+    echo "Try xrandr-dmenu without dmenu, and you're gonna have a bad time." >&2
+    exit 255
+  elif ! xset q &>/dev/null; then
+    echo 'Woah there, cowboy! You need to run this from inside X!' >&2
+    exit 1
+  fi
 }
 
+function initialize_globals() {
+  local output
+
+  XRANDR_TXT="$(xrandr)"
+  for output in $(grep ' connected' <<< "${XRANDR_TXT}" | cut -d ' ' -f 1); do
+    OUTPUT_CONFIGURED[${output}]='false'
+  done
+  XRANDR_CMD='xrandr'
+}
+
+initialize_globals
+readonly XRANDR_TXT
 main
 
-## END OF FILE #################################################################
-# vim filetype=zsh autoindent expanddtab shiftwidth=2 tabstop=2
+################################################################################
+# vim filetype=zsh autoindent expandtab shiftwidth=2 tabstop=2
 # End
 #
